### PR TITLE
Adding GPU ops

### PR DESCRIPTION
**Pull request by dfm**
WIP

### CODE REVIEW

**Comment by dfm** [comment]
On flatiron machines:

```bash
module load cuda/11.0.3_450.51.06 cmake/3.19.1
pip install -U jax jaxlib==0.1.57+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html
cmake . -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build
cp build/gpu_driver*.so src/exoplanet_core/jax/
```

Then to run:

```bash
export XLA_FLAGS=--xla_gpu_cuda_data_dir=/cm/shared/sw/pkg/devel/cuda/11.0.3_450.51.06
```

**Comment by dylex** [comment]
I had to set `CMAKE_INSTALL_PREFIX` for jenkins (user install) in e6e333b -- you might want to review this.

**Comment by dfm** [comment]
@dylex: Yes - that's right, I'd been meaning to fix that. Thanks!

**Comment by dfm** [comment]
Thanks again @dylex!

**Pull request merged**
